services:
  mvp-story-seeker:
    container_name: mvp-story-seeker
    image: matejv30/mvp-story-seeker:${TAG_NAME}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - mvp-nw

networks:
  mvp-nw:
    external: true

