services:
  mvp-storyseeker-dev:
    container_name: mvp-storyseeker-dev
    build:
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - "3010:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_GATEWAY=${NEXT_PUBLIC_API_GATEWAY}
      - NODE_ENV=development
    env_file:
      - .env
