FROM node:18

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the source code
COPY . .

# Expose the development port
EXPOSE 3000

# Run Next.js in development mode
CMD ["npm", "run", "dev"]