services:
  storyseeker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: storyseeker-dev
    ports:
      - "3001:3000"
    volumes:
      - ~/projects/storyseeker:/usr/src/app
    env_file:
      - .env.local
    command: npm run dev