name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --build-arg NEXT_PUBLIC_CORE_API_URL=${{ secrets.NEXT_PUBLIC_CORE_API_URL }} -t storyseeker .

      - name: Tag Docker image
        run: |
          docker tag storyseeker "${{ secrets.DOCKER_USERNAME }}/storyseeker:latest"

      - name: Push Docker image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/storyseeker:latest"

      - name: SSH to server and run Docker container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |  
            docker pull "${{ secrets.DOCKER_USERNAME }}/storyseeker:latest"
            
            docker stop storyseeker || true
            docker rm storyseeker || true
            
            docker run -d \
              --restart unless-stopped \
              -p 3000:3000 \
              --name storyseeker \
              ${{ secrets.DOCKER_USERNAME }}/storyseeker:latest
